### ISSUE TITLE
[cfp] comments and suggestions

### ISSUE THREAD

**Issue by wseltzer** [w3c/web-wcg-hdr-workshop#1]
Thanks Chris! 

Can we call out a clearer high-level goal than: 
> The primary goal of the workshop is to bring together browser vendors, content creators, color scientists, and experts in other relevant areas (e.g. accessibility, scripting, security, web) to converge on technologies for enabling WCG and HDR on the Open Web Platform.

Perhaps start with some of the recent developments in color management that call for corresponding updates to the Web platform, or some of the experiences that could be enabled by improved color on the Web. 

Is there a call to action? 

This is an acronym-heavy field! Spell out Wide Color Gamut (WCG) and High Dynamic Range (HDR) the first time the initialisms are used. For review by those less expert, maybe use hyperlinks to provide references for some of the other terms?

**Comment by svgeesus** [comment]
Looking at, for example [W3C/OGC Joint Workshop Series on Maps for the Web](https://www.w3.org/2020/maps/) or [W3C Workshop on Web and Machine Learning](https://www.w3.org/2020/06/machine-learning-workshop/) I see that (besides an eye-catching hero graphic) there are separate tabs for Overview and Call for Participation. That leaves a lot more room for the explanation and motivation.

I agree that this is needed.

**Comment by svgeesus** [comment]
An [overview, explaining WCG and HDR, has been added](https://www.w3.org/Graphics/Color/Workshop/)
