### ISSUE TITLE
How to registrate?

### ISSUE THREAD

**Issue by ppaalanen** [w3c/web-wcg-hdr-workshop#4]
https://www.w3.org/Graphics/Color/Workshop/cfp.html asks interested people to registrate, but does not explain how or where. I'm not planning to be a speaker.

I'm working on https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14 and this W3C workshop sounds like it could be very educating.

**Comment by therahedwig** [comment]
I had the exact same question, as the Krita project is also very interested in these things (both because of us writing exporters and importers, but also because we need to advise artists on their color management pipeline, and export for web is pretty significant for that).

**Comment by therahedwig** [comment]
I found the registration thing: https://ti.to/wcg-hdr-ws/w3c-workshop-on-wcg-hdr

EDIT: It was linked from the agenda on the page.

**Comment by ppaalanen** [comment]
Oh, in the "Important Dates" box. Ok.

Wouldn't hurt to have the link in the "How can I attend" section too.

**Comment by svgeesus** [comment]
The link is in the "Participate in the workshop! " box, as well. 

However, thanks for the suggestion, I will add a link to "How can I attend" section as well.
