### ISSUE TITLE
Scrollbar issue in embedded videos

### ISSUE THREAD

**Issue by chrisn** [w3c/web-wcg-hdr-workshop#8]
In my browser, embedded videos such as [this one](https://www.w3.org/Graphics/Color/Workshop/slides/talk/cava) have scroll bars that rapidly appear and disappear, creating a unpleasant flickering effect.

**Comment by svgeesus** [comment]
Hmm, I'm not seeing that (Firefox 91.0a1/Win10, Chrome 93.0.4567.1/Win10). What browser and platform?

**Comment by chrisn** [comment]
Edge 91.0.864.67 and Chrome 91.0.4472.124 on Windows 10 both show the problem. Firefox 89.02 is OK. Display resolution is 3840x2160.

**Comment by svgeesus** [comment]
Unable to reproduce in Chrome Version 97.0.4681.1 on Win 10 at the same resolution. Meanwhile we changed how we embed videos, so maybe that also fixed this issue?

**Comment by chrisn** [comment]
It seems OK for me now, so I think we can close this. Thanks
